### PR TITLE
Fix misuses read and write pointers

### LINKED ISSUE #18: Performance Improvement: W5500
From the original project:

> I don't now if there is a difference, but with W5500, I was able to upload a 250k sketch to mega2560. it was so slow, so I reduced the #define TFTP_PACKET_DELAY to 20 ms. worth trying, I think..

Note from the author:

> With W5500 there is a possibility that you could remove the delay completely as it is. You don't encounter these issues with it because W5500 increments its socket buffer pointers internally, unlike W5100 and W5200.

Response from the issue filer:

> in my tests i was able to go down to 5 ms with W5500.. I didn't try less that this

### LINKED ISSUE #19: Investigate: Ariadne Misuses W5100 and W5200
From original project:

From @davidhaenggi on February 9, 2015 14:40
Hi
I downloaded the Ariadne-Bootloader to use it with a OpenMediaController.
It's based on a Atmega2560 and includes a Wiznet W5100 ethernet chip.
In general the bootloader works great, thanks for the nice work.
While trying to upload bigger firmware files I was running into the "64-Package" Problem.
For me it looks like the arduino is receiving a completely messed up message instead of package number 64. When it tries to read the source IP address of the package it gets some random IP and therefor tries to send a response to this random IP. Thats why the Wiznet chip tries to reach to gateway, because the random IP is not in its IP range.
* The solution to set the gateway address to the same IP as the TFTP client was not satisfying to me, as I would like to send firmwares from different client-IPs.
* As a workaround I did some modification to the code:
1. Don't set return IP address and port if the message is not a valid tftp message. I moved the regarding code to the end of funtion processPacket() and add some validation check.
```
-  // Set up return IP address and port
    * uint8_t i;
    * for(i = 0; i < 6; i++) spiWriteReg(REG_S3_DIPR0 + i, buffer[i]);
+ // only set return address if paket received is wellformed, to avoid sending to random IP address.
    * if(returnCode != ERROR_INVALID && returnCode != ERROR_UNKNOWN){
    * // Set up return IP address and port
    * uint8_t i;
    * for(i = 0; i < 6; i++) spiWriteReg(REG_S3_DIPR0 + i, buffer[i]);
    * }
```
2. And I added the same validation check before sending any response messages in tftpPoll().
```
+ if(response != ERROR_INVALID && response != ERROR_UNKNOWN)
sendResponse(response);
```
Like this the arduino does not send any error for packet 64. The client repeats the packet and the transfer continues. With this changes I was able to set the TFTP_PACKET_DELAY to 0 and have a fast tftp transfer without any failures.
I know this is not a proper solution, but it works for me and I thought it may help someone.

### PR DESCRIPTION
**Pull request by hagaigold**
## Description

Fix misuse of read pointer `REG_S3_RX_RD0 ` & write pointer `REG_S3_TX_WR0` for WIZnet shields: W5100 & W5200.
As a result of this fix, `tftpPoll` function, which processing each new packet, was simplified, and the too-long delay, `TFTP_PACKET_DELAY`, in each iteration of `tftpPoll` function was reduced to 5ms (was 400ms).

Fixes #19
Fixes #18 

other changes:
- max address, `MAX_ADDR`, of code area fixed to match the makefile
- global (extern) variables definition

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
see issue #19 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

File: avr/bootloaders/athena/src/debug/debug_main.h [hunk 1]
```diff
@@ -22,25 +22,33 @@ const unsigned char mDebugMain_PREFIX[] PROGMEM = "Main: ";
...
+#if defined(__WIZ_W5100__)
+#define TITLE_WIZ_TYPE "W5100"
+#elif defined(__WIZ_W5200__)
+#define TITLE_WIZ_TYPE "W5200"
+#elif defined(__WIZ_W5500__)
+#define TITLE_WIZ_TYPE "W5500"
+#endif
+
+const unsigned char mDebugMain_TITLE[] PROGMEM =
+	TITLE_BOARD_TYPE " (" TITLE_WIZ_TYPE "), Version " PP_STRINGIFY(BUILD_TAG);
```
Comment (phillipjohnston) [inline avr/bootloaders/athena/src/debug/debug_main.h:49]: Really like this new approach!

File: avr/bootloaders/athena/src/ethernet/tftp.h [hunk 2]
```diff
@@ -51,17 +51,13 @@
 #define TFTP_PACKET_MAX_SIZE \
 	(UDP_HEADER_SIZE + TFTP_OPCODE_SIZE + TFTP_BLOCKNO_SIZE + TFTP_MAX_PAYLOAD)
 
-#define TFTP_PACKET_DELAY 400
+#define TFTP_PACKET_DELAY 5
```
Comment (phillipjohnston) [inline avr/bootloaders/athena/src/ethernet/tftp.h:54]: Big improvement

**Review by phillipjohnston — APPROVED** [review]
Great work!

**Comment by hagaigold** [comment]
> Great work!

thx :)

regarding the `TFTP_PACKET_DELAY `- I did tests with a `0` delay but left a `5` for "just in case" (don't have all the different boards & WIZs)
